### ISSUE TITLE
Precompile Time explodes with v2.0.0

### ISSUE THREAD

**Issue by waldie11** [SciML/NonlinearSolve.jl#223]
I am using NonlinearSolve as a dependency from OrdinaryDiffEq.jl
Iam used to see OrdinaryDiffEq being a heavy dependency in the precompile phase. Pulling in NonlinearSolve on v2.0.0 is however skyrocketing precompile time - increasing also precompile time for packages depending on it.

Starting from this setup from a plain `.julia` environment, precompile is finished within 4min on my machine. After dropping the restriction on <2.0.0 Iam giving up after 5min only seeing NonlinearSolve and not even starting with OrdinaryDiffEq. I have seen it finish already, but I didnt time it then (and am not going to do it again) and think its in the region of 30min.
```toml
name = "short_test"
uuid = "ac54827c-5042-4dc0-8a8e-9aaad1679992"

[deps]
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"

[compat]
NonlinearSolve = "<2.0.0"

[weakdeps]
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"
```

```julia
  [8913a72c] ↑ NonlinearSolve v1.10.1 ⇒ v2.0.0
Precompiling project...
  Progress [>                                        ]  0/3
  ◓ NonlinearSolve
```
